name: popcornpals
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^1.2.2
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/curio.png
